### ISSUE TITLE
Animation Editor: "RenderStepped event can only be used from local scripts"

### ISSUE THREAD

**Issue by TheNexusAvenger** [ROBLOX/Studio-Tools#14]
16:37:10.379 - RenderStepped event can only be used from local scripts
16:37:10.379 - Script 'Plugin_144373835.Plugin.JointEditor', Line 234
16:37:10.380 - Stack End

Repro steps:
1. Have animation editor plugin installed and up to date
2. Start a server or do game:GetService("NetworkServer")
3. Error appears in output

Idea for fix,Replace line 234 with this:
if game:FindFirstChild("NetworkServer") then
    game:GetService'RunService'.Stepped:wait()
else
    game:GetService'RunService'.RenderStepped:wait()
end

**Comment by RobloxCodeWriter** [comment]
This part of the plugin has been removed and should no longer be causing any issues.
