### ISSUE TITLE
Terrain Generation GUI isn't working

### ISSUE THREAD

**Issue by alieneila** [ROBLOX/Studio-Tools#30]
I've dropped the terrain tools into the startergui folder and when I test play it seems all of the GUI windows show stacked on each other by default. After turning on and back off each individual tool, you are left with the Generation window which has no options and the buttons are unclickable. I'm guessing there should be a button at the bottom to turn this on and off as well, but there isn't a button in the bottom bar like there are with the other tools.

**Comment by Stickmasterluke** [comment]
The smooth terrain tools are not intended to be put into startergui.

**Comment by alieneila** [comment]
Oh okay, I'm sorry. I was just going by the instructions on the wiki... http://wiki.roblox.com/index.php?title=Smooth_terrain#How_to_add_the_Smooth_Terrain_Tools_to_your_game

Is there any reason the generate function doesn't generate correctly when using it outside of the studio GUI? https://forum.roblox.com/Forum/ShowPost.aspx?PostID=189594387

**Comment by Stickmasterluke** [comment]
Good find! The documentation on the wiki was wrong. If you want the terrain tools to function as in-game tools, you need to put them into the *StarterPack. I will update the wiki. Thanks
