### ISSUE TITLE
Can't Install Plugins

### ISSUE THREAD

**Issue by VerberoRBLX** [ROBLOX/Studio-Tools#42]
Not sure if this is where this should go, but I can't install any ROBLOX plugins from studio. I click the "Install" button and nothing  happens.

**Comment by ghost** [comment]
Did you open a new studio tab, after you installed the plugins?

**Comment by einsteinK** [comment]
I have the same, but I replace the QtWebKit4.dll so I don't know if I "made" that bug for myself.
Basicly what happens: I press "Install" and literally nothing happens.
No "Open a new place" in the output, not even a loading animation or page refresh.
It just seems as if the button isn't actually connected to anything, just a decoration.

**Comment by Drummerboy12567** [comment]
I open plugins perfectly today so i think it is fixed
