### ISSUE TITLE
License

### ISSUE THREAD

**Issue by ghost** [ROBLOX/Studio-Tools#5]
The tools are published on GitHub, but they are [not open source](http://opensource.org/) because they cannot be used, changed and shared. It would be nice if they were released under a free license (see [GitHub's choosealicense.com](http://choosealicense.com/)). This would require approval from all the people who contributed to the code so far (@einsteinK, @Stickmasterluke, @tberg-roblox and @DarraghGriffin), so it's better to do it early.

**Comment by einsteinK** [comment]
Doesn't the copyright state we can use/change/install them in ROBLOX Studio?
(or the client, anything owned by ROBLOX Corporation)

**Comment by ghost** [comment]
@einsteinK Nope.

At the moment we aren't allowed to reuse code from these tools in games or to modify them and use the modified versions.

**Comment by tberg-roblox** [comment]
@mark-otaris 
Committed to public domain. Feel free to do what you want with it, just don't hold us liable.
