### ISSUE TITLE
Pre-Smooth Terrain places with a part called Terrain break tools

### ISSUE THREAD

**Issue by Silent137-zz** [ROBLOX/Studio-Tools#7]
Having a pre-smooth terrain place with a part called Terrain causes the Convert to Smooth button to break

17:12:56.438 - IsSmooth is not a valid member of Part
17:12:56.438 - Script 'Plugin_-1.Terrain Tools.TerrainBrushScript', Line 6
17:12:56.438 - Stack End

**Comment by TheNexusAvenger** [comment]
My guess is this is the issue.

while not workspace:WaitForChild('Terrain').IsSmooth do 
    workspace.Terrain.Changed:wait() 
end 

It probably waits for the first instance with the name "Terrain" instead of trying to reference the property in Workspace.

**Comment by einsteinK** [comment]
`Property Object Workspace.Terrain [readonly]`
Also, isn't the Terrain always there, like a service?
It doesn't get replicated, only its contents and the voxels, no?

**Comment by zeux** [comment]
When we were working on smooth terrain we had an issue with plugin initialization order - plugin scripts would run very very early when creating a file, before Terrain object was there at all. Thus WaitForChild.

I fixed this since so probably this is not important any more...

**Comment by DarraghGriffin** [comment]
That means the issue can be fixed as in my pull request?

It worked when I tested it so I assume it is fine.
